apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: vectorization-service
spec:
  output:
    to:
      kind: ImageStreamTag
      name: vectorization-service:latest
  source:
    git:
      uri: https://github.com/Joel-hanson/vectorization-service.git  # Update this with your repo
      ref: main
    contextDir: /
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
  runPolicy: Serial